# Generated by Django 3.1.3 on 2020-11-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('father_fname', models.CharField(max_length=30)),
                ('father_lname', models.CharField(max_length=30)),
                ('building_soc_name', models.CharField(max_length=30)),
                ('house_flat_no', models.CharField(max_length=10)),
                ('landmark', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('mob_no', models.CharField(max_length=10)),
                ('landline', models.CharField(max_length=8)),
                ('bday', models.DateField()),
                ('gender', models.CharField(max_length=8)),
                ('education', models.CharField(max_length=30)),
                ('institutename', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
