# Generated by Django 3.1.3 on 2020-11-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_table',
            name='landmark',
            field=models.CharField(max_length=40),
        ),
    ]
