# Generated by Django 3.1.3 on 2020-11-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_details', '0002_auto_20201118_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_table',
            name='institutename',
            field=models.CharField(max_length=60),
        ),
    ]
